apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: gameofthrones-deployment 
spec: 
  selector: 
    matchLabels: 
      app: gameofthrones 
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: gameofthrones 
    spec: 
      containers: 
      - name: gameofthrones 
        image: sahitkumarreddy/game-of-thrones:latest
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: gameofthrones-service 
spec: 
  selector: 
    app: gameofthrones 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer